### ISSUE TITLE
sched panic

### ISSUE THREAD

**Issue by zhu312542860** [dhilipkumars/MrRedis#53]
i run the sched process panic。

[root@open-falcon mr-redis]# ./sched
2017/01/10 21:18:56 [config.go:314] [W] open /tmp/mr-redis/conf/app.conf: no such file or directory
2017/01/10 21:18:56 Configuration file is = {127.0.0.1:5050 ./MrRedisExecutor ./redis-server zookeeper 127.0.0.1:2181 stderr 127.0.0.1 5454 5656}
2017/01/10 21:18:56 *****************************************************************
2017/01/10 21:18:56 *********************Starting MrRedis-Scheduler******************
2017/01/10 21:18:56 *****************************************************************
2017/01/10 21:18:56 Starting the HTTP server at port 5656
2017/01/10 21:18:56 [asm_amd64.s:1721] [I] http server Running on :5656
2017/01/10 21:18:56 Hosting artifact './MrRedisExecutor' at 'http://127.0.0.1:5454/MrRedisExecutor'
2017/01/10 21:18:56 Hosting artifact './redis-server' at 'http://127.0.0.1:5454/redis-server'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x4b563c]

goroutine 8 [running]:
github.com/mesos/mr-redis/sched/mesoslib.GetFrameWorkID(0x0, 0x0, 0xc8200f5d50)
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/mesoslib/mesoslib.go:141 +0x6c
github.com/mesos/mr-redis/sched/mesoslib.Run(0xc8200f5cc0, 0xe, 0xc8200f5d40, 0x9, 0xc8200f5d50, 0x4, 0xc82019c1e0, 0x11, 0xf24a10, 0xe, ...)
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/mesoslib/mesoslib.go:170 +0x11d
created by main.main
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/main.go:100 +0x920

goroutine 1 [chan receive]:
github.com/astaxie/beego.(*App).Run(0xc8200f4400)
	/home/ubuntu/dev/sched/Godeps/_workspace/src/github.com/astaxie/beego/app.go:171 +0x33d
github.com/astaxie/beego.Run(0xc8200f3af8, 0x1, 0x1)
	/home/ubuntu/dev/sched/Godeps/_workspace/src/github.com/astaxie/beego/beego.go:277 +0x17d
github.com/mesos/mr-redis/sched/httplib.Run(0xc8200f5d60, 0x4)
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/httplib/httplib.go:240 +0x1d8
main.main()
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/main.go:112 +0x98c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x13eaaa0)
	/home/ubuntu/dev/sched/Godeps/_workspace/src/github.com/golang/glog/glog.go:882 +0x67
created by github.com/golang/glog.init.1
	/home/ubuntu/dev/sched/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 9 [runnable]:
github.com/mesos/mr-redis/sched/cmd.Creator()
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/cmd/Creator.go:12
created by main.main
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/main.go:103 +0x938

goroutine 10 [runnable]:
github.com/mesos/mr-redis/sched/cmd.Maintainer()
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/cmd/Maintainer.go:12
created by main.main
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/main.go:106 +0x950

goroutine 11 [runnable]:
github.com/mesos/mr-redis/sched/cmd.Destoryer(0xc8200f5cc0)
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/cmd/Destroyer.go:15
created by main.main
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/main.go:109 +0x968

goroutine 12 [IO wait]:
net.runtime_pollWait(0x7fcf4d2ca420, 0x72, 0xc82000a1c0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82020b020, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82020b020, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82020afc0, 0x0, 0x7fcf4d2ca518, 0xc82020c100)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820026208, 0xc820037d58, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820026208, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820018600, 0x7fcf4d2ca4e0, 0xc820026208, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820018600, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1877 +0x136
github.com/astaxie/beego.(*App).Run.func4(0xc8200f4400, 0xc8201c1b80, 0xc82020af50)
	/home/ubuntu/dev/sched/Godeps/_workspace/src/github.com/astaxie/beego/app.go:159 +0x487
created by github.com/astaxie/beego.(*App).Run
	/home/ubuntu/dev/sched/Godeps/_workspace/src/github.com/astaxie/beego/app.go:166 +0x9a5

goroutine 14 [runnable]:
github.com/mesos/mr-redis/sched/mesoslib.prepareExecutorInfo.func1(0xc8200f5d40, 0x9, 0xc8200f5d50, 0x4)
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/mesoslib/mesoslib.go:54
created by github.com/mesos/mr-redis/sched/mesoslib.prepareExecutorInfo
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/mesoslib/mesoslib.go:66 +0x583
[root@open-falcon mr-redis]#

**Comment by dhilipkumars** [comment]
Hi @zhu312542860 how did you get 'Sched' binary? did you build it yourself?

**Comment by zhu312542860** [comment]
I get the Schedule binary through this method:
$mkdir mr-redis
$cd mr-redis
$wget https://github.com/mesos/mr-redis/releases/download/v0.01-alpha/sched
$wget https://github.com/mesos/mr-redis/releases/download/v0.01-alpha/MrRedisExecutor

**Comment by dhilipkumars** [comment]
@zhu312542860 
Give me a couple of days, ill update the binary.  Thats an outdated one.
In the meantime if you want you could build it from the source, which has got latest code change and i dont think it would crash. (Atleast im unable to re-produce it)

**Comment by JinsYin** [comment]
@dhilipkumars I have also experienced the same error while i am using "DBType":"**zookeeper**"

**Comment by Daniel-ltw** [comment]
👍 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x4b563c]

goroutine 20 [running]:
github.com/mesos/mr-redis/sched/mesoslib.GetFrameWorkID(0x0, 0x0, 0xf160e8)
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/mesoslib/mesoslib.go:141 +0x6c
github.com/mesos/mr-redis/sched/mesoslib.Run(0xc8201f4d80, 0x28, 0xc8201f4e10, 0x2c, 0xf160e8, 0x4, 0xc8201072c0, 0x1c, 0xc820107300, 0x19, ...)
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/mesoslib/mesoslib.go:170 +0x11d
created by main.main
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/main.go:100 +0x920

goroutine 1 [runnable]:
strings.Map(0x10e8498, 0xc820107ce0, 0x14, 0x0, 0x0)
	/usr/local/go/src/strings/strings.go:432 +0xb7
strings.ToLower(0xc820107ce0, 0x14, 0x0, 0x0)
	/usr/local/go/src/strings/strings.go:477 +0x43
mime.ParseMediaType(0xc820107ce0, 0x14, 0x0, 0x0, 0x2, 0x0, 0x0)
	/usr/local/go/src/mime/mediatype.go:106 +0xe9
mime.setExtensionType(0xc8201eb170, 0x4, 0xc820107ce0, 0x14, 0x0, 0x0)
	/usr/local/go/src/mime/type.go:166 +0x52
mime.loadMimeFile(0xf24c10, 0xf)
	/usr/local/go/src/mime/type_unix.go:43 +0x3b8
mime.initMimeUnix()
	/usr/local/go/src/mime/type_unix.go:53 +0x88
mime.initMime()
	/usr/local/go/src/mime/type.go:80 +0x64
sync.(*Once).Do(0x1412ed0, 0x10e7b20)
	/usr/local/go/src/sync/once.go:44 +0xe4
mime.AddExtensionType(0xf15130, 0x4, 0xf3c8f0, 0xe, 0x0, 0x0)
	/usr/local/go/src/mime/type.go:161 +0x1f6
github.com/astaxie/beego.initMime(0x0, 0x0)
	/home/ubuntu/dev/sched/Godeps/_workspace/src/github.com/astaxie/beego/mime.go:564 +0xcd
github.com/astaxie/beego.initBeforeHttpRun()
	/home/ubuntu/dev/sched/Godeps/_workspace/src/github.com/astaxie/beego/beego.go:295 +0x1f6
github.com/astaxie/beego.Run(0xc820143af8, 0x1, 0x1)
	/home/ubuntu/dev/sched/Godeps/_workspace/src/github.com/astaxie/beego/beego.go:271 +0x140
github.com/mesos/mr-redis/sched/httplib.Run(0xf160f0, 0x4)
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/httplib/httplib.go:240 +0x1d8
main.main()
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/main.go:112 +0x98c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 18 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x13eaaa0)
	/home/ubuntu/dev/sched/Godeps/_workspace/src/github.com/golang/glog/glog.go:882 +0x67
created by github.com/golang/glog.init.1
	/home/ubuntu/dev/sched/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 21 [chan receive]:
github.com/mesos/mr-redis/sched/cmd.Creator()
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/cmd/Creator.go:22 +0x95
created by main.main
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/main.go:103 +0x938

goroutine 22 [chan receive]:
github.com/mesos/mr-redis/sched/cmd.Maintainer()
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/cmd/Maintainer.go:22 +0xb2
created by main.main
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/main.go:106 +0x950

goroutine 23 [chan receive]:
github.com/mesos/mr-redis/sched/cmd.Destoryer(0xc8201f4d80)
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/cmd/Destroyer.go:20 +0x95
created by main.main
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/main.go:109 +0x968

goroutine 35 [runnable]:
github.com/mesos/mr-redis/sched/mesoslib.prepareExecutorInfo.func1(0xc8201f4e10, 0x2c, 0xf160e8, 0x4)
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/mesoslib/mesoslib.go:54
created by github.com/mesos/mr-redis/sched/mesoslib.prepareExecutorInfo
	/home/ubuntu/gopkg/src/github.com/mesos/mr-redis/sched/mesoslib/mesoslib.go:66 +0x583
W0228 16:12:51.536767 28920 logging.cpp:91] RAW: Received signal SIGTERM from process 1588 of user 0; exiting
```
